server:
  port: 8765
  ssl:
    key-store: file:D:/Codes/taco-cloud/tacocloud-restapi/src/main/resources/mykeys.jks
    key-store-password: tacoweb
    key-password: tacoweb
spring:
  thymeleaf:
    cache: false
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  jms:
    template:
      default-destination: tacocloud.order.queue
  kafka:
    bootstrap-servers:
      - localhost:2181
    template:
      default-topic: tacocloud.orders.topic
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: tacocloud_kitchen
      properties:
        spring.json.trusted.packages: tacos

  h2:
    console:
      enabled: true
  artemis:
    host: artemis.tacocloud.com
    port: 61617
    user: tacoweb
    password: l3tm31n
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: sa

logging:
  path: /var/logs/
  level:
    root: WARN
    org.springframework.security: DEBUG

greeting:
  message: hello testing descrition
