server:
  port: 8765
  ssl:
    key-store: file:D:/Codes/taco-cloud/src/main/resources/mykeys.jks
    key-store-password: tacoweb
    key-password: tacoweb
spring:
  thymeleaf:
    cache: false
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: sa

logging:
  path: /var/logs/
  level:
    root: WARN
    org.springframework.security: DEBUG

greeting:
  message: hello testing descrition
